### ISSUE TITLE
Error with Kotlin plugin version

### ISSUE THREAD

**Issue by a-leblond** [AgoraIO/Flutter-RTM#1]
Hi,

When trying to build, i got this error 

`* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':agora_rtm' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71`

It seems that my Kotlin Gradle plugin version doesn't match yours.
Is there any way you can upgrade the kotlin dependency of agora_rtm ?

Thanks in advance !

**Comment by PRWrl** [comment]
Bump kotlin to 1.3.0:  https://github.com/AgoraIO/Flutter-RTM/commit/d17a7e97aa0bf26de906d0dcc9459ffcb0ef1222

Published 0.9.3 to pub.dev

**Comment by a-leblond** [comment]
Thanks, problem solved !
