### ISSUE TITLE
用最新的master版本，flutter pub get 『agora_rtm: ^0.9.7』出现问题

### ISSUE THREAD

**Issue by luckmlc** [AgoraIO/Flutter-RTM#10]
Running "flutter pub get" in meili...                            0.8s
Couldn't read file LocalFile: '/Users/mayer/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtm-0.9.7/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

[✓] Flutter (Channel master, v1.10.17-pre.59, on Mac OS X 10.14.6 18G1012, locale zh-Hans-CN)
    • Flutter version 1.10.17-pre.59 at /Users/mayer/development/flutter
    • Framework revision 9e0df259df (5 hours ago), 2019-11-11 15:56:43 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0

**Comment by plutoless** [comment]
Couldn't read file LocalFile: '/Users/mayer/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtm-0.9.7/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

看下文件权限？

**Comment by luckmlc** [comment]
> Couldn't read file LocalFile: '/Users/mayer/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtm-0.9.7/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
> 
> 看下文件权限？

不太清楚文件权限有什么问题，我把

/Users/mayer/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtm-0.9.7

这个目录删除了，重新 "flutter pub get" 也报这个错哦。

**Comment by plutoless** [comment]
看他错误的描述是文件存在，但读不了，你可以到目录下面 ls -alt看下文件权限

**Comment by luckmlc** [comment]
MayerdeMacBook-Pro:agora_rtm mayer$ pwd
/Users/mayer/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtm-0.9.7/android/src/main/kotlin/io/agora/agora_rtm
MayerdeMacBook-Pro:agora_rtm mayer$ ls -lt
total 88
-rw-r--r--  1 mayer  staff  24642  8 20 17:12 AgoraRtmPlugin.kt
-rw-r--r--  1 mayer  staff   2289  8 20 17:12 RTMChannel.kt
-rw-r--r--  1 mayer  staff   8746  8 20 17:12 RTMClient.kt

**Comment by luckmlc** [comment]
> 看他错误的描述是文件存在，但读不了，你可以到目录下面 ls -alt看下文件权限

MayerdeMacBook-Pro:agora_rtm mayer$ pwd
/Users/mayer/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtm-0.9.7/android/src/main/kotlin/io/agora/agora_rtm
MayerdeMacBook-Pro:agora_rtm mayer$ ls -lt
total 88
-rw-r--r-- 1 mayer staff 24642 8 20 17:12 AgoraRtmPlugin.kt
-rw-r--r-- 1 mayer staff 2289 8 20 17:12 RTMChannel.kt
-rw-r--r-- 1 mayer staff 8746 8 20 17:12 RTMClient.kt


看看，这权限有问题么

**Comment by luckmlc** [comment]
> 看他错误的描述是文件存在，但读不了，你可以到目录下面 ls -alt看下文件权限

和这个文件的权限没关系哦， 我改成777了 pub get 还是报原来的错

-rwxrwxrwx  1 mayer  staff  24642  8 20 17:12 AgoraRtmPlugin.kt

**Comment by plutoless** [comment]
https://github.com/flutter/flutter/issues/42923
@luckmlc 看下这个

**Comment by luckmlc** [comment]
> [flutter/flutter#42923](https://github.com/flutter/flutter/issues/42923)
> @luckmlc 看下这个

看这个issue是cloud_functions插件更新之后才解决的吧，我要怎么试呢

**Comment by plutoless** [comment]
用flutter channel 命令切换下flutter版本
用stable或者beta试试

**Comment by luckmlc** [comment]
> 用flutter channel 命令切换下flutter版本
> 用stable或者beta试试

stable 上是好的，master上得把agora_rtm 插件删掉才行。

主要stable上flutter还有一些底层bug没修复，想用master版本来着，发现agora_rtm又用不了😂

**Comment by luckmlc** [comment]
> 用flutter channel 命令切换下flutter版本
> 用stable或者beta试试

兄弟，你们啥时候能更新个版本呀

**Comment by plutoless** [comment]
这个channel是flutter版本的channel吧，我们更新版本好像不解决问题？

**Comment by luckmlc** [comment]
对，是flutter版本的channel，不过你发的flutter/flutter#42923 这个issue，看是对插件更新版本后解决的，flutter的master这几天更新了很多版本，每次更新我都试了，还是报你们这个插件的错误呢。

**Comment by luckmlc** [comment]
@plutoless  兄弟，这个有办法解决么？你那边用master或者dev版本试是正常的么

**Comment by plutoless** [comment]
我今晚看一下

**Comment by luckmlc** [comment]
> 我今晚看一下

好的，谢谢

**Comment by plutoless** [comment]
你能发个最小复现demo给我吗？我跑了下没问题，我也看了下那个issue里感觉是source目录没设对但我们的库应该没这个问题

**Comment by luckmlc** [comment]
你那边切到master没有问题么，说的source目录是指什么，我这边和flutter代码没关系，我用默认的demo都有问题，只要加上 agora_rtm: ^0.9.7  这个库，flutter pub get就执行不下去，还没走到运行调试的时候。

**Comment by luckmlc** [comment]
> 你能发个最小复现demo给我吗？我跑了下没问题，我也看了下那个issue里感觉是source目录没设对但我们的库应该没这个问题

找大佬请教了下，说需要插件方这边跟随flutter团队对flutter tools的修改做改动，麻烦看下这个

https://github.com/flutter/flutter/blob/cb614d13394125ea8dcdc1ebcb7f03da22f59fc2/packages/flutter_tools/lib/src/platform_plugins.dart#L97-L106

简单来说 新建kotlin文件夹 然后把XXXPlugin.kt 移动到kotlin文件夹下 其他文件都不用动 然后gradle里设置src。


可参考这个： https://github.com/CaiJingLong/flutter_ijkplayer/pull/160

**Comment by luckmlc** [comment]
@plutoless 兄弟，有解决方案了，麻烦有空帮忙看看

**Comment by luckmlc** [comment]
flutter 今天出了 1.12 stable 正式版，更新后agora_rtm这个插件用不了了，有时间能更新修复一下这个问题么 @plutoless  😩😩😩

**Comment by iyuhang** [comment]
更新 flutter 到1.12.13+hotfix.5之后出了同样的问题

Couldn't read file LocalFile: '/Users/apple/.pub-cache/git/Flutter-RTM-b2c0e705a1fd8eb518369b456ccc5664375db9ba/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
Exited (1)

**Comment by luckmlc** [comment]
@plutoless  现在怎么样啦，有计划时间修复这个问题么？

**Comment by iyuhang** [comment]
@plutoless Flutter RTM 什么时候能修复呀？

**Comment by LichKing-2234** [comment]
@iyuhang 这个问题已经修复了，预计下午会发版本

**Comment by LichKing-2234** [comment]
> flutter 今天出了 1.12 stable 正式版，更新后agora_rtm这个插件用不了了，有时间能更新修复一下这个问题么 @plutoless 😩😩😩

这个问题已经修复了，预计下午会发版本

**Comment by LichKing-2234** [comment]
@luckmlc 这个问题已经修复了，预计下午会发版本

**Comment by luckmlc** [comment]
> @luckmlc 这个问题已经修复了，预计下午会发版本

太好了，谢谢，期待😀

**Comment by iyuhang** [comment]
@LichKing-2234 

为什么我的还是这样，我把 agorartm 这个文件夹删除了，也是这样

Running "flutter pub get" in fixtime...                             2.2s
Couldn't read file LocalFile: '/Users/apple/.pub-cache/git/Flutter-RTM-b2c0e705a1fd8eb518369b456ccc5664375db9ba/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

**Comment by LichKing-2234** [comment]
> @LichKing-2234
> 
> 为什么我的还是这样，我把 agorartm 这个文件夹删除了，也是这样
> 
> Running "flutter pub get" in fixtime... 2.2s
> Couldn't read file LocalFile: '/Users/apple/.pub-cache/git/Flutter-RTM-b2c0e705a1fd8eb518369b456ccc5664375db9ba/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

请问你用的哪个版本

**Comment by LichKing-2234** [comment]
> > @LichKing-2234
> > 为什么我的还是这样，我把 agorartm 这个文件夹删除了，也是这样
> > Running "flutter pub get" in fixtime... 2.2s
> > Couldn't read file LocalFile: '/Users/apple/.pub-cache/git/Flutter-RTM-b2c0e705a1fd8eb518369b456ccc5664375db9ba/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
> 
> 请问你用的哪个版本
看样子是本地有缓存？

**Comment by iyuhang** [comment]
已经解决了，之前pubspect.yaml一直用的 git的链接方式，还用 pub的版本号方式就好了


 
---原始邮件---
发件人: "Arthas"<notifications@github.com>
发送时间: 2019年12月20日(星期五) 晚上8:02
收件人: "AgoraIO/Flutter-RTM"<Flutter-RTM@noreply.github.com>;
抄送: "Ansen"<ansen@fixtime.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [AgoraIO/Flutter-RTM] 用最新的master版本，flutter pub get 『agora_rtm: ^0.9.7』出现问题 (#10)


  
@LichKing-2234
 为什么我的还是这样，我把 agorartm 这个文件夹删除了，也是这样
 Running "flutter pub get" in fixtime... 2.2s
 Couldn't read file LocalFile: '/Users/apple/.pub-cache/git/Flutter-RTM-b2c0e705a1fd8eb518369b456ccc5664375db9ba/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
  
请问你用的哪个版本
 看样子是本地有缓存？

**Comment by LichKing-2234** [comment]
@iyuhang ok:smile:
