### ISSUE TITLE
Facing Auth issue while CI-CD pipeline.

### ISSUE THREAD

**Issue by bimaldave13** [AgoraIO/Flutter-RTM#18]
Hi Team,

First of all, appreciate the great effort.
When I try to add this library it works fine but it creates an issue on the CI-CD pipeline for unauthorized access.  Please suggest what to do for resolving that issue.

thanks,
bimal

**Comment by plutoless** [comment]
im not sure what kind of unauthorized access you are getting but it sounds like it has nothing to do with our sdk. if you believe they do have connections, please post your error log so that we can take a look.

**Comment by bimaldave13** [comment]
HI plutoless,
Thanks for your quick response.
I got below error when I try to compile.
**Compile Error**
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

***
In my .yaml file, I have added this as a dependency **agora_rtm: ^0.9.7**
 please let me know if i am on wrong way.

**Comment by plutoless** [comment]
this apparently tells you that your CI/CD pipeline failed to pull code from github. usually its because your ssh key is not properly configured on your CI system.

**Comment by bimaldave13** [comment]
HI plutoless,

I am using flutter and if set the dependency using .yaml file than why it gives an error. My all other dependency working fine.  Not even in CI-Cd but after upgrade my Mac os i face this issue on compile-time as well.  In old Os, it working fine.

**Comment by bimaldave13** [comment]
HI plutoless,

Its issue of the Mac OS command line. Please find the solution as below.
Run below command:

- **flutter clean**

- **flutter pub cache repair**

- **flutter run --verbose**

it will resolve the issue of SDK installation. you can close this issue.

thanks for your quick help.

thanks,
bimal

**Comment by plutoless** [comment]
good to know, thanks @bimaldave13
