### ISSUE TITLE
Error With Kotlin Version

### ISSUE THREAD

**Issue by rlee1990** [AgoraIO/Flutter-RTM#19]
I'm receiving an error that states: 
`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':agora_rtm' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0`

**Comment by rlee1990** [comment]
Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.1)
[√] Connected device (1 available)

• No issues found!

**Comment by LichKing-2234** [comment]
please remove `ext.kotlin_version = '1.3.0'` from your `agora_rtom/build.gradle`
we will modify and upload later

**Comment by LichKing-2234** [comment]
try to use version `0.9.9`

**Comment by rlee1990** [comment]
@LichKing-2234 are u asking to have me try kotlin version 0.9.9 or the plugin?

**Comment by LichKing-2234** [comment]
plugin

**Comment by rlee1990** [comment]
@LichKing-2234 thanks that worked.

**Comment by rlee1990** [comment]
@LichKing-2234 Now when I try to launch I get this error 
`[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: No implementation found for int io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String) (tried Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog and Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog__ILjava_lang_String_2)
E/flutter (13057): 	at io.agora.rtc.internal.RtcEngineImpl.nativeLog(Native Method)
E/flutter (13057): 	at io.agora.rtc.internal.Logging.log(Logging.java:25)
E/flutter (13057): 	at io.agora.rtc.internal.Logging.i(Logging.java:49)
E/flutter (13057): 	at io.agora.rtc.internal.RtcEngineImpl.checkIfInUIThread(RtcEngineImpl.java:155)
E/flutter (13057): 	at io.agora.rtc.RtcEngine.CreateRendererView(RtcEngine.java:881)
E/flutter (13057): 	at io.agora.agorartcengine.AgoraRenderViewFactory.create(AgoraRenderViewFactory.java:22)
E/flutter (13057): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:174)
E/flutter (13057): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:550)
E/flutter (13057): 	at android.app.Dialog.show(Dialog.java:391)
E/flutter (13057): 	at android.app.Presentation.show(Presentation.java:267)
`

**Comment by rlee1990** [comment]
If I remove just that plugin it runs for the live stream.

**Comment by LichKing-2234** [comment]
it looks like the system can't find the RTC SDK .so file, what have you done?

**Comment by rlee1990** [comment]
@LichKing-2234 i just imported the package in and added the items just as they were added in the example but when I click the button that launches the live stream and the rtc channel it crashes with that error

**Comment by rlee1990** [comment]
@LichKing-2234 this is what I do:
`Future<void> _initAgoraRtcEngine() async {
    _client = await AgoraRtmClient.createInstance(HBTV.API_KEY);
    await AgoraRtcEngine.create(HBTV.API_KEY);
    await AgoraRtcEngine.registerLocalUserAccount(
        {"appId": HBTV.API_KEY, "userAccount": widget.uid});
    await AgoraRtcEngine.enableVideo();
    await AgoraRtcEngine.enableAudio();
    await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
  }
`

**Comment by rlee1990** [comment]
@LichKing-2234 any updates on this?

**Comment by LichKing-2234** [comment]
AgoraRtcEngine init before AgoraRtmClient, this is a bug, we will fix later

**Comment by rlee1990** [comment]
@LichKing-2234 That works thanks. Any timetable on the fix?
