### ISSUE TITLE
Send channel message

### ISSUE THREAD

**Issue by rlee1990** [AgoraIO/Flutter-RTM#21]
Is it designed that the sender of the channel message does not receive the message also on the channel onMessageReceived listener?

**Comment by LichKing-2234** [comment]
yes, local can't receive the message, only remote, you can use `resultCallback`

**Comment by rlee1990** [comment]
@LichKing-2234 I am not seeing `resultCallback` are you referring to `channel.sendMessage(AgoraRtmMessage.fromText(msg))` if so it only returns a void.

**Comment by LichKing-2234** [comment]
your can try-catch
```
Future<void> sendMessage(AgoraRtmMessage message) async {
    final res = await _callNative("sendMessage", {'message': message.text});
    if (res["errorCode"] != 0) throw AgoraRtmChannelException("sendMessage failed errorCode:${res['errorCode']}", res['errorCode']);
  }
```

**Comment by rlee1990** [comment]
@LichKing-2234 I am not following. Where are you getting _callNative from? or any of this.

**Comment by LichKing-2234** [comment]
this is method body of `sendMessage`

**Comment by rlee1990** [comment]
@LichKing-2234 so are you saying wrap my channel.sendMessage(AgoraRtmMessage.fromText(msg)) in a try catch block?

**Comment by LichKing-2234** [comment]
yes, the catch mean sendMessage failed

**Comment by bst102user** [comment]
I am receiving message twice and next time 3 times any solution
