### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by iyuhang** [AgoraIO/Flutter-RTM#22]
我在0.9.8下正常运行，升级到0.9.9后，就出以下错了>

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/apple/.pub-cache/hosted/pub.dartlang.org/agora_rtm-0.9.9/android/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating project ':agora_rtm'.
> Could not get unknown property 'kotlin_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Gradle task assembleDebug failed with exit code 1

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by iyuhang** [comment]
yaml 里重新改回到 0.9.8能正常运行

我的 build.gradle 是这样的，因为从flutter 1.9.8升级过来

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' &&
                    !details.requested.name.contains('androidx')) {
                details.useVersion "1.0.1"
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by LichKing-2234** [comment]
请看readme，0.9.9开始，kotlin版本由主工程配置，你的主工程的kotlin_version没有配置

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
