### ISSUE TITLE
Flutter sendLocalInvitation的问题

### ISSUE THREAD

**Issue by huangred** [AgoraIO/Flutter-RTM#24]
在Flutter SDK中 sendLocalInvitation相关方法在AgoraRtmClient中
在API的参考文档中，是出现在RtmCallManager中
在目前的Flutter SDK版本中，sendLocalInvitation等相关方式是不是暂时还不能调用？

另外，建议更新Flutter SDK的时候，把example也针对性的更新一下，不然有些方法传递的是Map<dynamic, dynamic>类型的参数，都不知道要传递的是什么。
谢谢。

**Comment by LichKing-2234** [comment]
目前Flutter SDK没有同步native SDK，后面会同步的

**Comment by LichKing-2234** [comment]
flutter的sendLocalInvitation在flutter这边封装了下，实际里面就是调用RtmCallManager的sendLocalInvitation

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
