### ISSUE TITLE
在 iOS 上重启卡死

### ISSUE THREAD

**Issue by iyuhang** [AgoraIO/Flutter-RTM#25]
RTM 0.9.9 运行在 iOS 上，点击 restart （Hot Reload 不会出现）两到三次就会出现应用卡死，没有日志输出
移出 RTM 后恢复正常
请问能有什么原因吗？

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.42.1)
[✓] Connected device (2 available)

**Comment by LichKing-2234** [comment]
你用的真机么，我用模拟器貌似没出现过

**Comment by iyuhang** [comment]
@LichKing-2234 对的，用的真机，在 iphone7 iphonexs 上都出现过了

**Comment by plutoless** [comment]
@iyuhang 如果我们这边复现不了的话可能比较难调查，有什么别的信息吗

**Comment by iyuhang** [comment]
@plutoless 我先关闭问题，有别的信息时，再反馈
