### ISSUE TITLE
E/AGORA_SDK(30488): cannot open log file for writing: agorartm.log, err=30

### ISSUE THREAD

**Issue by iyuhang** [AgoraIO/Flutter-RTM#27]
flutter 1.12.13+hotfix.8
一加7plus
console 一直打印这个日志错误

E/AGORA_SDK(30488): cannot open log file for writing: agorartm.log, err=30
E/AGORA_SDK(30488): cannot open log file for writing: agorartm.log, err=30
E/AGORA_SDK(30488): cannot open log file for writing: agorartm.log, err=30
E/AGORA_SDK(30488): cannot open log file for writing: agorartm.log, err=30

**Comment by LichKing-2234** [comment]
这个是没有文件写权限

**Comment by iyuhang** [comment]
怎么能解决呢
我已经试过 ：
重启电脑 、手机，彻底卸载重装 app
flutter pub repair, 重建所有插件

**Comment by LichKing-2234** [comment]
Android权限设置里给读写文件的权限

**Comment by LichKing-2234** [comment]
或者用代码申请

**Comment by JoannaGong** [comment]
@LichKing-2234 我给了权限，也是这样报错，是我给的权限不对吗？
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**Comment by LichKing-2234** [comment]
@JoannaGong 不仅如此，还需要代码申请

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
