### ISSUE TITLE
Add enableHistoricalMessaging to sendmessage

### ISSUE THREAD

**Issue by mstolk** [AgoraIO/Flutter-RTM#28]
Hi,

I really would like the enableHistoricalMessaging property on the sendMessage method, can anyone help me with this?

kind regards,

Marco

**Comment by plutoless** [comment]
hi marco, i'm sorry but enableHistoricalMessaging feature is not yet available officially out of china. you may find it on our doc site but that is a mistake. we are fixing the docs and we will do this as soon as it's officially supported.

**Comment by LichKing-2234** [comment]
added 0.9.14
