### ISSUE TITLE
插件注册问题

### ISSUE THREAD

**Issue by huangred** [AgoraIO/Flutter-RTM#30]
android\app\src\main\kotlin\com\example\stargazer_client_fish\MainActivity.kt文件里，如果不注释掉GeneratedPluginRegistrant.registerWith(flutterEngine);这行代码，则视频通话时黑屏。

注释掉的话，导致其他插件（flutter_webview_plugin: ^0.3.10+1）又报错（提示插件未注册）

运行环境
agora_rtc_engine: ^1.0.5
agora_rtm: ^0.9.9
flutter version：v1.15.21

**Comment by LichKing-2234** [comment]
你的activity是继承`io.flutter.embedding.android.FlutterActivity`么，去掉该代码是官方推荐的做法

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
