### ISSUE TITLE
 onLeaveChannel的问题

### ISSUE THREAD

**Issue by huangred** [AgoraIO/Flutter-RTM#31]
在原生api文档中，调用leavchannel后会回调onLeaveChannel，在onLeaveChannel中会有RtcStats统计信息，但在Flutter SDK中，onLeaveChannel是没有任何参数的。
1. 在Flutter SDK中是不是还没有实现？
2. 在Futter SDK中还是有其他方法获取统计信息？如有，望告知一下。

谢谢！

另外，
在原生api文档中，
void io.agora.rtc.IRtcEngineEventHandler.onUserOffline (  int uid, int reason )第二个参数是reason
但在flutter sdk中
static void Function(int uid, int elapsed) onUserOffline; 第二个参数是elapsed
有点疑惑。

**Comment by plutoless** [comment]
onLeaveChannel的参数应该是在最新版本加入的，我们正在计划flutter sdk的升级，会在下个版本对齐这些接口

**Comment by LichKing-2234** [comment]
3.x version support it
