### ISSUE TITLE
flutter build apk and open it. Then it crash quickly.

### ISSUE THREAD

**Issue by JoannaGong** [AgoraIO/Flutter-RTM#32]
I clone your demo to my pc and just change agora appId. it works nomally if running on my phone. however, if I run 'flutter build apk' and install into my photo. It will crash quickly.
My flutter version is '1.12.13+hotfix.8'. 
I prepare to release my app and found this problem.  So I tried your demo...

**Comment by LichKing-2234** [comment]
any crash log?

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.

**Comment by jayeshpansheriya** [comment]
i face same issue.
any solution of there?
