### ISSUE TITLE
sendMessageToPeer offline message

### ISSUE THREAD

**Issue by casti** [AgoraIO/Flutter-RTM#34]
Hello,

Using `sendMessageToPeer(peerid, msg, false)` method to send message to an offline peer throws error code 3 which means **"3: The user is offline and has not received the peer-to-peer message."**. 

I also tried making the last argument to `true` but same error thrown. Looking at the API there's an option: 
> ['boolean io.agora.rtm.SendMessageOptions.enableOfflineMessaging = false'](https://docs.agora.io/en/Real-time-Messaging/API%20Reference/RTM_java_linux/classio_1_1agora_1_1rtm_1_1_send_message_options.html#a924ef8c28e7a1d41a215a7331e284330)

 By default the value is `false`. Is this already implemented and if so how can I enable it in Flutter SDK?

Thanks

**Comment by LichKing-2234** [comment]
added 0.9.14
