### ISSUE TITLE
已经申请了储存权限，日志一直打印cannot open log file for writing

### ISSUE THREAD

**Issue by iyuhang** [AgoraIO/Flutter-RTM#36]
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

///获取读存储权限
PermissionHandler().requestPermissions([PermissionGroup.storage]);
```

```
E/AGORA_SDK(18819): cannot open log file for writing: /storage/emulated/0/com.fixtime.yuyu/agorartm.log, err=13
E/AGORA_SDK(18819): cannot open log file for writing: /storage/emulated/0/com.fixtime.yuyu/agorartm.log, err=13
E/AGORA_SDK(18819): cannot open log file for writing: /storage/emulated/0/com.fixtime.yuyu/agorartm.log, err=13
E/AGORA_SDK(18819): cannot open log file for writing: /storage/emulated/0/com.fixtime.yuyu/agorartm.log, err=13
E/AGORA_SDK(18819): cannot open log file for writing: /storage/emulated/0/com.fixtime.yuyu/agorartm.log, err=13
E/AGORA_SDK(18819): cannot open log file for writing: /storage/emulated/0/com.fixtime.yuyu/agorartm.log, err=13
```

flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G87, locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
(base) AnsenMBP-4:fixtime apple$

**Comment by LichKing-2234** [comment]
是高版本Android么，默认不允许写入sdcard的

**Comment by iyuhang** [comment]
安卓十，一加7pro
不是已经申请权限了吗，这个太烦人了





------------------ 原始邮件 ------------------
发件人: Arthas <notifications@github.com&gt;
发送时间: 2020年4月23日 17:58
收件人: AgoraIO/Flutter-RTM <Flutter-RTM@noreply.github.com&gt;
抄送: Ansen <ansen@fixtime.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[AgoraIO/Flutter-RTM] 已经申请了储存权限，日志一直打印cannot open log file for writing (#36)





 
是高版本Android么，默认不允许写入sdcard的

**Comment by LichKing-2234** [comment]
参考下这个
https://blog.csdn.net/Anhe0901/article/details/103018915

或者设置日志到应用包的cache目录
