### ISSUE TITLE
How can i enable the history in beta api.i need the history of all message i sent in channel

### ISSUE THREAD

**Issue by sherin80** [AgoraIO/Flutter-RTM#39]
i want  to get the history of all message sent in my channel. i am current use the beta api for getting message  but no message showing.is any way to get history of all message

**Comment by LichKing-2234** [comment]
the history restful API is close beta now.

**Comment by sherin80** [comment]
then how can i save the old message from this

**Comment by plutoless** [comment]
sorry this feature is currently not available for GDPR compliance. if you definitely need this and you believe you are clear from GDPR compliance, you may try talking to our sales.
