### ISSUE TITLE
Cannot Open log file for writing agorartm.log, err=30

### ISSUE THREAD

**Issue by pr-1** [AgoraIO/Flutter-RTM#40]
I am trying to login into a rtm channel using the following code - 
The client gets Logged In but i keep getting this error on my console. 
I followed the example code with changed ids and tokens.

Future<void> initialize() async { 
_client = await AgoraRtmClient.createInstance(AppEnvironment.agoraAppId);   
  _client.onMessageReceived = (AgoraRtmMessage message, String peerId) {
  print('message received');
     };
     _client.onConnectionStateChanged = (int state, int reason) {
       print('csdcsd');
     };
     try { 
      await _client.login(_agoraRtmProvider.rtmToken.token, _agoraRtmProvider.rtmToken.uid);
       print('login success');
     }catch(e) {
       print('login error');
       print(e.toString());
     }
   }

**Comment by pr-1** [comment]
This is the log that i get. The last Line keeps on repeating --- 

I/flutter (22204): on connection state changed
I/flutter (22204): login success
I/flutter (22204): on connection state changed
E/AGORA_SDK(22204): cannot open log file for writing: agorartm.log, err=30
E/AGORA_SDK(22204): cannot open log file for writing: agorartm.log, err=30
E/AGORA_SDK(22204): cannot open log file for writing: agorartm.log, err=30
E/AGORA_SDK(22204): cannot open log file for writing: agorartm.log, err=30

**Comment by pr-1** [comment]
Output of Flutter Doctor is. - 

Princes-Air:edvi_flutter princesrivastava$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.17.1 at /Users/princesrivastava/Projects/Flutter/flutter
    • Framework revision f7a6a7906b (11 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/princesrivastava/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/princesrivastava/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • SM M305F • 32009b3747ef26ab • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by plutoless** [comment]
have you granted permission for writing file? looks like a permission issue

**Comment by pr-1** [comment]
YOU MEAN THIS -- 
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
??

**Comment by plutoless** [comment]
i think you also have to dynamically request it when needed in code.

**Comment by pr-1** [comment]
Yup got that done. It was some sequencing error, i was not logging into the channel before joining.
Went through the official docs and library code. Thanks for the help. I am closing this now.
