### ISSUE TITLE
运行IOS错误 找不到AgoraRtm_iOS 1.2.2 版本

### ISSUE THREAD

**Issue by TBoyLi** [AgoraIO/Flutter-RTM#42]
![image](https://user-images.githubusercontent.com/14815341/89713641-9e8f4780-d9cb-11ea-9364-094c5a03077e.png)

![image](https://user-images.githubusercontent.com/14815341/89713505-a4385d80-d9ca-11ea-8348-a17f568f197d.png)

**Comment by LichKing-2234** [comment]
需要执行`pod repo update`
