### ISSUE TITLE
What is the user id

### ISSUE THREAD

**Issue by boucoding** [AgoraIO/Flutter-RTM#44]
I am asking what should I write in the user id field in the sample app?

**Comment by LichKing-2234** [comment]
it can be your system user id or any unique value.

**Comment by boucoding** [comment]
I know I wrote it but it give me that login failed

**Comment by LichKing-2234** [comment]
any error log? maybe your appId enabled app certificate, and you forget to add token?

**Comment by boucoding** [comment]
Probably this is what happened, thank you! I will try now

**Comment by plutoless** [comment]
please reopen if issue is not resolved

**Comment by av2ry-1030** [comment]
> any error log? maybe your appId enabled app certificate, and you forget to add token?

It's maybe also my case, where should I add the token?

**Comment by LichKing-2234** [comment]
@av2ry-1030 when you call `joinChannel`
