### ISSUE TITLE
RTM Client Work in background

### ISSUE THREAD

**Issue by mohit67890** [AgoraIO/Flutter-RTM#46]
I am trying to build the chat application but want the RTM Client to work in the background to listed to the RTM messages. 
Is there a way to make RTM client as a service that works also when the app is terminated. 
Or, is there a way to accumulate the messages when the user is offline..

**Comment by LichKing-2234** [comment]
RTM offline message is closed beta.

**Comment by mohit67890** [comment]
Thank You..
