### ISSUE TITLE
现在 pub 上是0.9.6 github 上是1.0.1？ 

### ISSUE THREAD

**Issue by iyuhang** [AgoraIO/Flutter-RTM#5]
什么时候能更新呢
另外发送文件、媒体、历史消息、这些功能什么时候能上呢

**Comment by plutoless** [comment]
这些功能需要主板先支持 这边可以找销售或客户询问一下

**Comment by plutoless** [comment]
1.1我们最近安排一下

**Comment by Matrixbirds** [comment]
请问你是在找1.0.1的native适配版本吗？目前pub的0.9.6就是适配的1.0.1全native api @iyuhang

**Comment by iyuhang** [comment]
@plutoless @Matrixbirds 好的
