### ISSUE TITLE
The `agora_rtm` pod failed 

### ISSUE THREAD

**Issue by evaschalde** [AgoraIO/Flutter-RTM#50]
- ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | license: Missing license type.
    - WARN  | [iOS] keys: Missing primary key for `source` attribute. The acceptable ones are: `git, hg, http, svn`.

**Comment by FacuRossi** [comment]
Hi Guys, @Matrixbirds @LichKing-2234 @PRWrl @masashi-sutou 
 
I fixed the issue on this [PR](https://github.com/AgoraIO/Flutter-RTM/pull/51)

Can you take a look? We need this change in order to go make a realese into the App Store.

Thanks.

**Comment by evaschalde** [comment]
Guys, the temporary solution is to go back to agora_rtm 0.9.12

**Comment by LichKing-2234** [comment]
fixed 0.9.14
