### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by DineshTaral123** [AgoraIO/Flutter-RTM#54]
Connection state changed: 2, reason: 1

**Comment by LichKing-2234** [comment]
you can refer to this doc. state 2 means connecting.
https://docs.agora.io/en/Real-time-Messaging/API%20Reference/RTM_java/interfaceio_1_1agora_1_1rtm_1_1_rtm_client_listener.html#a9b6f86cb2d7d5ec4adf0b6d645c16bf9
