### ISSUE TITLE
添加用户属性失败 addOrUpdateLocalUserAttributes failed errorCode:3

### ISSUE THREAD

**Issue by LiangJinMing66** [AgoraIO/Flutter-RTM#57]
` Map<String, String> info = {`
 `       "name":"test"`
 `     };`
`await _client.addOrUpdateLocalUserAttributes([info]);`

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: addOrUpdateLocalUserAttributes failed errorCode:3
E/flutter (25007): #0      AgoraRtmClient.addOrUpdateLocalUserAttributes (package:agora_rtm/src/agora_rtm_client.dart:294:7)

**Comment by LichKing-2234** [comment]
你的参数有问题，应该
```
Map<String, String> info1 = {
"key":"xxx",
"value":"xxx"
};
Map<String, String> info2 = {
"key":"xxx",
"value":"xxx"
};
await _client.addOrUpdateLocalUserAttributes([info1, info2]);
```

**Comment by LiangJinMing66** [comment]
好的,谢谢
