### ISSUE TITLE
关于 channel 的几个问题

### ISSUE THREAD

**Issue by iyuhang** [AgoraIO/Flutter-RTM#6]
1.用于实现群的需求，但看这个限制，只能同时创建20个不同的频道，这个会影响群的创建个数吗？？

> RTM 支持同时创建最多 20 个不同的频道实例并加入到多个频道中，但是每个频道实例必须使用不同的频道 ID 以及不同的回调。

2.一个 channel 一旦创建之后，是不是只要不调用 release 就会一直存在，在 channel 内的用户都能收到消息？用户在 channel 里的关系是否一直保留的呢？

3.channel 点对点的 消息是支持漫游的吗：用户当时不线，几天后登录能再收到消息吗？如果是漫游的，保存时间是多长？

4.类似群的场景，加入了很多个channel 后，需要建立每个对应 channel 的监听，来收消息吗？

**Comment by plutoless** [comment]
1. Rtm没有群的概念，频道同时只能创建20个
2. 是的，你release只是release自己的channel对象并从channel离开，并不影响channel本身
3. 频道消息不支持离线，点对点消息支持，离线消息的保存时间请参考文档
4. 是的 如果想收对应频道的群消息，必须加入频道并监听

**Comment by iyuhang** [comment]
1.同时创建最多20个是针对单个用户而言的吧？即每个用户可同时加入或者创建总共20个频道？但总数其实是不限20个？

**Comment by Matrixbirds** [comment]
问题1: 首先这里的channel只是rtm即时消息的频道抽象 你在集成的时候应该设计好自己的“组”业务，描述就是文档上就是
问题2: channel 这里的release 麻烦看下文档 这里的channel只是对象的内存管理 按照文档逻辑应该是leave或者logout以后才会停止收消息
问题3: 这里1.0.1 sdk的channel是没有离线消息的 只有点对点消息支持离线消息 不知道是不是这里你说的“漫游” 具体点对点消息的离线时间 请参照文档的描述
问题4: 这里你可以参考插件的设计代码 每一个channel是会根据不同的实例创建出来的独立对象 事件也是绑定在对应的对象上 所以这里也是需要 每个channel 绑定独立的事件

**Comment by plutoless** [comment]
是的 你登入rtm后 一个session内你只能同时加入20个频道，整体频道数没有限制

**Comment by iyuhang** [comment]
明白了
1.用着实现传统群的需求是不行的，因为用户很有可能加入超过20个群，而且需要每个加入过未解散的群都能收到消息。这个限制有必要吗，可以去除吗
4._client.onMessageReceived 只能监听到点对点的消息。 channel.onMessageReceived 能监听到 channel 的消息，加入多个 channel 需要每个都绑定独立事件，但消息监听我们需要做成一个全局的 provider，实现想来会比较麻烦。如果能在_client.onMessageReceived 这个 channel 的上层监听所有的 channel 消息，只是消息类型不同感觉会好一点？

**Comment by plutoless** [comment]
基本上RTM不是完全设计用来做IM功能的SDK，他和IM SDK还是有区别的，更多是为了和其他用户实时信号互动的作用，因此你提到的这些限制都是为了实现更低延时和更高互动性进而限制的东西
