### ISSUE TITLE
onRemoteInvitationReceived  被叫方收到视频邀请的问题

### ISSUE THREAD

**Issue by luckmlc** [AgoraIO/Flutter-RTM#9]
你好，想问一下被叫方收到主叫方的视频邀请事件，是用哪个？看android,ios原生的文档是onRemoteInvitationReceived，我在flutter-RTM里没有找到 onRemoteInvitationReceived 这个事件，只有onRemoteInvitationReceivedByPeer，但这个看源码注释是通知主叫方『被叫收到了邀请』 。

/// Callback to the caller: occurs when the callee receives the call invitation.
void Function(AgoraRtmRemoteInvitation invite) onRemoteInvitationReceivedByPeer;

**Comment by Matrixbirds** [comment]
这里就是对应 onRemoteInvitationReceived 你可以在[这里](https://github.com/AgoraIO/Flutter-RTM/blob/master/ios/Classes/RTMClient.m#L168)找到集成代码
